/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
// eng : Nouran Elshazly

typedef volatile unsigned int  vuint32_t ;
#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>

//gpio
#define GPIOA_BASE            0x40010800
#define GPIOA_CRH             *(volatile uint32_t *)(GPIOA_BASE + 0x04)
#define GPIOA_CRL             *(volatile uint32_t *)(GPIOA_BASE + 0x0)
#define GPIOA_ODR             *(volatile uint32_t *)(GPIOA_BASE + 0x0C)
//RCC
#define RCC_BASE              0x40021000
#define RCC_APB2RSTR         *(volatile uint32_t *)(RCC_BASE + 0x18)
#define RCC_CFGR             *(volatile uint32_t *)(RCC_BASE + 0x04)
#define RCC_CR               *(volatile uint32_t *)(RCC_BASE + 0x0)

//External Interrupt

#define EXTI_BASE            0x40010400
#define EXTI_IMR            *(volatile  uint32_t*)( EXTI_BASE+ 0x0)
#define EXTI_RTSR           *(volatile uint32_t *)(EXTI_BASE + 0x08)
#define EXTI_PR             *(volatile uint32_t *)( EXTI_BASE+ 0x14)

//AFIO
#define AFIO_BASE           0x40010000
#define AFIO_EXTICR1        *(volatile uint32_t *)( AFIO_BASE + 0x08)
#define NVIC_ISRER0         *(volatile uint32_t *)(0xE000E100)

void clock_init(){
//Enable GPIOA CLOCK
 RCC_APB2RSTR |= 1<<2;

 // ENABLE CLOCK FOR AFIO
 RCC_APB2RSTR|= (1<<0);
}

void  GPIO_init(){
// set pin 13 at port A as an output
GPIOA_CRH &= 0xFF0FFFFF;
GPIOA_CRH |= 0x00200000;

//PIN 0 PORTA FLOATING
GPIOA_CRL |= (1<<2);

}
int main (void )
{
	// EXTI x configuration (x= 0 ) to portA
	AFIO_EXTICR1=0

	// enable EXTI line 0 mask 1
	EXTI_IMR|=  (1<<0) ;

	// enable Rising edge
	EXTI_RTSR|= (1<<0);

	// Enable NVIC IRQ6

	NVIC_ISRER0 |=(1<<6);

       while(1);
       return 0 ;

}
void EXTIO_IRQHandler(void )
{
	//toggle led
	GPIOA_ODR ^=(1<<13);
	// Clear pending register
	EXTI_PR|= (1<<0);
}

